[project]
name = "Sensibility_Analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.3.0",
    "streamlit>=1.50.0",
    "yfinance>=0.2.66",
]
